// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_to_struct.proto

#include "proto_to_struct.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_proto_5fto_5fstruct_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_5fto_5fstruct_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_5fto_5fstruct_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_5fto_5fstruct_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_proto_5fto_5fstruct_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025proto_to_struct.proto\032 google/protobuf"
  "/descriptor.proto::\n\022write_eigen_helper\022"
  "\034.google.protobuf.FileOptions\030\240\234\001 \001(\010:8\n"
  "\020write_pcl_helper\022\034.google.protobuf.File"
  "Options\030\241\234\001 \001(\010:9\n\016eigen_typename\022\037.goog"
  "le.protobuf.MessageOptions\030\204\235\001 \001(\t:7\n\014pc"
  "l_typename\022\037.google.protobuf.MessageOpti"
  "ons\030\205\235\001 \001(\t:6\n\rinherits_from\022\035.google.pr"
  "otobuf.FieldOptions\030\350\235\001 \001(\010:1\n\010fix_size\022"
  "\035.google.protobuf.FieldOptions\030\351\235\001 \001(\005b\006"
  "proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_5fto_5fstruct_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_5fto_5fstruct_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_5fto_5fstruct_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_5fto_5fstruct_2eproto = {
  false, false, descriptor_table_protodef_proto_5fto_5fstruct_2eproto, "proto_to_struct.proto", 406,
  &descriptor_table_proto_5fto_5fstruct_2eproto_once, descriptor_table_proto_5fto_5fstruct_2eproto_sccs, descriptor_table_proto_5fto_5fstruct_2eproto_deps, 0, 1,
  schemas, file_default_instances, TableStruct_proto_5fto_5fstruct_2eproto::offsets,
  file_level_metadata_proto_5fto_5fstruct_2eproto, 0, file_level_enum_descriptors_proto_5fto_5fstruct_2eproto, file_level_service_descriptors_proto_5fto_5fstruct_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_5fto_5fstruct_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_5fto_5fstruct_2eproto)), true);
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  write_eigen_helper(kWriteEigenHelperFieldNumber, false);
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  write_pcl_helper(kWritePclHelperFieldNumber, false);
const std::string eigen_typename_default("");
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  eigen_typename(kEigenTypenameFieldNumber, eigen_typename_default);
const std::string pcl_typename_default("");
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  pcl_typename(kPclTypenameFieldNumber, pcl_typename_default);
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  inherits_from(kInheritsFromFieldNumber, false);
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< ::PROTOBUF_NAMESPACE_ID::int32 >, 5, false >
  fix_size(kFixSizeFieldNumber, 0);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
